WebApplication1/Controllers/CustomersController.cs
using System;
using System.Linq;
using System.Data.Entity;
using System.Web.Mvc;
using WebApplication1.Models;
using System.Net;
using PagedList;

namespace WebApplication1.Controllers
{
    public class CustomersController : Controller
    {
        private MovieDbContext db = new MovieDbContext();

        //GET: Customer 
        //public ActionResult Index()
        //{
        //    return View(db.Customers.ToList());
        //}

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var customers = from s in db.Customers
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                customers = customers.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    customers = customers.OrderByDescending(s => s.ID);
                    break;
                case "Date":
                    customers = customers.OrderBy(s => s.Dob);
                    break;
                case "date_desc":
                    customers = customers.OrderByDescending(s => s.Dob);
                    break;
                default:  // Name ascending 
                    customers = customers.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            var viewModel = customers.ToPagedList(pageNumber, pageSize);
            return View(viewModel);
        }
        
        [HttpGet]
        public ActionResult Create(string Title)
        {
            return View();
        }

        // Create New Customer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        //Get Details
        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //GET Edit Customer
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if ( id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST Edit Customer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        //GET Delete customer
        //[HttpGet]
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Customer customer = db.Customers.Find(id);
        //    if(customer == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(customer);
        //}

        ////POST Delete customer
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
      
        //public ActionResult Delete()
        //{
        //    return PartialView("_ModalDelete",null);
        //}

       
        public ActionResult DeleteConfirm(int id) //--> no jump to Delete Page
        {
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditModal (int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Modal",customer);
        }

        [HttpPost]
        public ActionResult EditModal(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_CustomerRow", customer);
            }
            //return View(customer);
            return new EmptyResult();
            // return partialView -> rows
        }

        [HttpGet]
        public ActionResult CreateModal()
        {
            Customer customer = new Customer();
            return PartialView("_ModalAdd",customer);
        }

        [HttpPost]
        public ActionResult CreateModal(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customer);
                db.SaveChanges();
                return PartialView("_CustomerRow", customer);
            }
            return new EmptyResult();
        }

        public ActionResult Search(string searchString)
        {
            var customers = db.Customers.Select(x => x);
            if (!String.IsNullOrEmpty(searchString))
            {
                customers = customers.Where(s => s.Name.Contains(searchString));
            }
            customers = customers.OrderBy(x => x.Name);
            var pageSize = 4;
            var pageNumber = 1;
            var listCustomer = customers.ToPagedList(pageNumber,pageSize);
            return PartialView("_CustomerList", listCustomer);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using PagedList;

namespace WebApplication1.Controllers
{
    public class MoviesController : Controller
    {
        public MoviesController()
        {
                
        }

        private MovieDbContext db = new MovieDbContext();

        // GET: Movies
        //public ActionResult Index(string movieGenre, string searchString)
        //{
        //    var GenreList = new List<string>();
        //    var GenreQry = db.Movies.OrderBy(x => x.Genre).Select(x => x.Genre);
        //    GenreList.AddRange(GenreQry.Distinct());
        //    ViewBag.movieGenre = new SelectList(GenreList);

        //    var movies = db.Movies.Select(s => s);
        //    if (!String.IsNullOrEmpty(searchString))
        //    {
        //        movies = movies.Where(s => s.Title.Contains(searchString));
        //    }
        //    if (!string.IsNullOrEmpty(movieGenre))
        //    {
        //        movies = movies.Where(x => x.Genre == movieGenre);
        //    }   
        //    return View(movies);
        //    //return View(db.Movies.ToList());
        //}

        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var movies = from s in db.Movies
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    movies = movies.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    movies = movies.OrderBy(s => s.ReleaseDate);
                    break;
                case "date_desc":
                    movies = movies.OrderByDescending(s => s.ReleaseDate);
                    break;
                default:  // Name ascending 
                    movies = movies.OrderBy(s => s.Title);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var viewModel = movies.ToPagedList(pageNumber, pageSize);
            return View(viewModel);
        }


       


        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,ReleaseDate,Genre,Price,Rating")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,ReleaseDate,Genre,Price,Rating")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/_CustomerList.cshtml
@model PagedList.IPagedList<WebApplication1.Models.Customer>
@using PagedList.Mvc;
@{
    ViewBag.Title = "_CustomerList";
}



<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Date Of Birth
        </th>
        <th>
            Gender
        </th>
        <th>
            Address
        </th>
        <th>
            PhoneNumber
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {

        @*@{Html.RenderPartial("_CustomerRow", item); }*@
        @Html.Partial("_CustomerRow", item)
    }


</table>


    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        <div class="container">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="@Url.Action("Index","Home")">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="@Url.Action("Index","Movies")">Movies <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Customers")">Customers</a>
                        </li>                        
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Modal.cshtml
@model WebApplication1.Models.Customer
@{
    ViewBag.Title = "_Modal";
}

@*<h2>_Modal</h2>*@

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalCenterTitle">Customer Info</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form action="@Url.Action("Edit","Customers")" method="post" class="form-control" id="customerForm">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ID)

        <div>
            <label>Name</label> <br />
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        </div>
        <div>
            <label>Date Of Birth</label><br />
            @Html.TextBoxFor(x => x.Dob, new { @class = "form-control" })
        </div>
        <div>
            <label>Gender</label><br />
            @Html.TextBoxFor(x => x.Gender, new { @class = "form-control" })
        </div>
        <div>
            <label>Address</label><br />
            @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
        </div>
        <div>
            <label>Phone Number</label><br />
            @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
        </div>
        <br />
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary bttSave" data-id="@Model.ID" data-url="@Url.Action("EditModal","Customers")">Save Edit</button>
</div>

WebApplication1/Views/Shared/_ModalAdd.cshtml
@model WebApplication1.Models.Customer
@{
    ViewBag.Title = "_Modal";
}

@*<h2>_Modal</h2>*@

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalCenterTitle">Customer Info</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form action="@Url.Action("CreateModal","Customers")" method="post" class="form-control" id="customerForm">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ID)

        <div>
            <label>Name</label> <br />
            @Html.EditorFor(x => x.Name, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div>
            <label>Date Of Birth</label><br />
            @Html.EditorFor(x => x.Dob, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div>
            <label>Gender</label><br />
            @Html.EditorFor(x => x.Gender, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div>
            <label>Address</label><br />
            @Html.EditorFor(x => x.Address, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div>
            <label>Phone Number</label><br />
            @Html.EditorFor(x => x.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <br />
    </form>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary bttSave" data-id="@Model.ID" data-url="@Url.Action("CreateModal","Customers")">Save</button>
</div>